---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: dis-authorisation-client-js

outputs:
  - name: build

run:
  path: dis-authorisation-client-js/ci/scripts/build.sh
